### ISSUE TITLE
Using copyright symbol causes an extra period when completing function calls

### ISSUE THREAD

**Issue by ccampbell** [Dan2552/SourceKittenSubl#19]
I was wondering what was going on. My files created by Xcode have a copyright symbol at the top and for some reason, this package does not like that.

Here is a screen capture to illustrate the issue:

![autocompletebug](https://cloud.githubusercontent.com/assets/259316/25980113/91485652-369a-11e7-8da0-431f5d268225.gif)

**Comment by Dan2552** [comment]
@ccampbell  @dielsonsales

This should now be resolved by https://github.com/Dan2552/SourceKittenSubl/pull/23
