### ISSUE TITLE
Inserting unnecessary point after selecting suggestion

### ISSUE THREAD

**Issue by dielsonsales** [Dan2552/SourceKittenSubl#20]
When I select a specific suggestion, by pressing `Enter`, the text ends with two points, such as:

```swift
variable..method();
```

Is this an issue of sublime or is the project doing something it shouldn't?

**Comment by Dan2552** [comment]
Probably the same issue as https://github.com/Dan2552/SourceKittenSubl/issues/19 

I'm not entirely sure, but it's possibly to do with byte size vs length. 

I did some quick testing but didn't find the solution today, if you want to have a bit of a play:
 https://github.com/Dan2552/SourceKittenSubl/commit/a0657decaab8e4cb27ca90dbd1dca11998122bbf

**Comment by dielsonsales** [comment]
Indeed it just happens when I have a `©` symbol in my comments. If I delete it, everything works normally as it should.

**Comment by Dan2552** [comment]
Thanks for checking. I'll close this one to avoid duplicates.
